/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_vs_php;

/**
 *
 * @author User
 */
public class java_php extends javax.swing.JApplet {
private int skorjava = 0;
    private int skorphp = 0;
    /**
     * Initializes the applet bahasa_favorit
     */
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(java_php.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(java_php.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(java_php.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(java_php.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelpersenjava = new javax.swing.JLabel();
        labelpersenphp = new javax.swing.JLabel();
        labeljudul = new javax.swing.JLabel();
        labelsukajava = new javax.swing.JLabel();
        labeljava = new javax.swing.JLabel();
        labelphp = new javax.swing.JLabel();
        labelsukaphp = new javax.swing.JLabel();
        btnphp = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        persenjavaphp = new javax.swing.JProgressBar();
        btnjava = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelpersenjava.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        labelpersenjava.setText("%");
        labelpersenjava.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labelpersenjava, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 100, -1));

        labelpersenphp.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        labelpersenphp.setText("%");
        labelpersenphp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labelpersenphp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 100, -1));

        labeljudul.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        labeljudul.setText("Bahasa Pemrograman Favorit");
        jPanel1.add(labeljudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        labelsukajava.setFont(new java.awt.Font("Times New Roman", 0, 50)); // NOI18N
        labelsukajava.setText("0");
        jPanel1.add(labelsukajava, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        labeljava.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        labeljava.setText("Java");
        jPanel1.add(labeljava, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        labelphp.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        labelphp.setText("PHP");
        jPanel1.add(labelphp, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        labelsukaphp.setFont(new java.awt.Font("Times New Roman", 0, 50)); // NOI18N
        labelsukaphp.setText("0");
        jPanel1.add(labelsukaphp, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        btnphp.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btnphp.setText("Suka");
        btnphp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnphpActionPerformed(evt);
            }
        });
        jPanel1.add(btnphp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        btnreset.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        jPanel1.add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, -1, -1));

        persenjavaphp.setForeground(new java.awt.Color(0, 51, 255));
        jPanel1.add(persenjavaphp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 350, 40));

        btnjava.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btnjava.setText("Suka");
        btnjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjavaActionPerformed(evt);
            }
        });
        jPanel1.add(btnjava, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void btnphpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnphpActionPerformed
        for (int counter =1; counter<=1; counter++){
            skorphp = ++skorphp;
        }
        labelsukaphp.setText(String.valueOf(skorphp));
        persenjavaphp.setMaximum(skorjava+skorphp);
        persenjavaphp.setValue(skorjava);
        
        labelpersenjava.setText(String.format("%.1f",persenjavaphp.getPercentComplete()*100)+"%");
        labelpersenphp.setText(String.format("%.1f",(1-persenjavaphp.getPercentComplete())*100)+"%");

    }//GEN-LAST:event_btnphpActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        skorjava=0;
        skorphp=0;
        labelsukaphp.setText(String.valueOf(skorphp));
        labelsukajava.setText(String.valueOf(skorjava));
        persenjavaphp.setMaximum(100);
        persenjavaphp.setValue(0);
        labelpersenjava.setText("%");
        labelpersenphp.setText("%");
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjavaActionPerformed
        for (int counter =1; counter<=1; counter++){
            skorjava = ++skorjava;
        }
        labelsukajava.setText(String.valueOf(skorjava));
        persenjavaphp.setMaximum(skorjava+skorphp);
        persenjavaphp.setValue(skorjava);
        
        labelpersenjava.setText(String.format("%.1f",persenjavaphp.getPercentComplete()*100)+"%");
        labelpersenphp.setText(String.format("%.1f",(1-persenjavaphp.getPercentComplete())*100)+"%");
    }//GEN-LAST:event_btnjavaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnjava;
    private javax.swing.JButton btnphp;
    private javax.swing.JButton btnreset;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labeljava;
    private javax.swing.JLabel labeljudul;
    private javax.swing.JLabel labelpersenjava;
    private javax.swing.JLabel labelpersenphp;
    private javax.swing.JLabel labelphp;
    private javax.swing.JLabel labelsukajava;
    private javax.swing.JLabel labelsukaphp;
    private javax.swing.JProgressBar persenjavaphp;
    // End of variables declaration//GEN-END:variables
}
